import './style.css';
import data from './data/github.json';
import { describe, selectRepos } from './catalog.js';

const repos = data.repos.map(describe);
const counts = { projects: repos.filter(r => !r.fork).length, forks: repos.filter(r => r.fork).length };
const state = { tab: location.hash === '#forks' ? 'forks' : 'projects', query: '', language: '', sort: 'curated' };
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]);
const icon = (name, size = 18) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({ arrow:'<path d="M7 17 17 7M7 7h10v10"/>', search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>', grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>', fork:'<circle cx="6" cy="4" r="2"/><circle cx="18" cy="4" r="2"/><circle cx="6" cy="20" r="2"/><path d="M6 6v12M18 6v3a5 5 0 0 1-5 5H6"/>', github:'<path d="M9 19c-5 1-5-2-7-2m14 5v-4a3.5 3.5 0 0 0-1-3c4-.5 7-2 7-6a5 5 0 0 0-1.5-3.5A5 5 0 0 0 20 2s-1.5-.5-4 1a14 14 0 0 0-8 0C5.5 1.5 4 2 4 2a5 5 0 0 0-.5 3.5A5 5 0 0 0 2 9c0 4 3 5.5 7 6a3.5 3.5 0 0 0-1 3v4"/>', pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>', star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2-5.5-2.9-5.5 2.9 1-6.2L3 9.6l6.2-.9Z"/>' })[name] || ''}</svg>`;

function artwork(r) {
  switch (r.art) {
    case 'hanzi': return '<div class="hanzi-pad"><span class="pad-corner">手写 / HANDWRITE</span><b>漢</b><span class="pen-dot"></span></div><div class="translation"><span>漢</span><div><b>hàn</b><small>Chinese · Han</small></div><span>↗</span></div>';
    case 'chess': return `<div class="chessboard">${Array.from({length:64}, (_,i) => `<i class="${(Math.floor(i/8)+i%8)%2 ? 'dark' : ''}">${({ 3:'♚', 9:'♟', 14:'♟', 18:'♞', 27:'♙', 35:'♘', 42:'♙', 46:'♙', 59:'♔' })[i] || ''}</i>`).join('')}</div><span class="art-chip">YOUR MOVE.</span>`;
    case 'pose': return '<span class="camera-label">● &nbsp; POSE TRACKING</span><svg class="pose-drawing" viewBox="0 0 320 200" fill="none"><ellipse cx="160" cy="182" rx="78" ry="8" fill="#bacbb1" opacity=".3"/><g stroke="#69845b" stroke-width="20" stroke-linecap="round"><path d="m144 67-22 28-41-23m95-5 27 28 39-23M154 111l-27 32-27 33m65-65 26 32 27 33"/><path d="m158 65 1 48" stroke-width="37"/></g><circle cx="160" cy="37" r="19" fill="#69845b"/><g stroke="#dcfda9" stroke-width="2"><path d="m81 72 41 23 24-30 28 0 29 30 39-23M146 65l6 46-25 32-27 33m74-111-9 46 26 32 27 33M152 111h13"/></g><g fill="#efffd5">'+[[81,72],[122,95],[146,65],[174,65],[203,95],[242,72],[152,111],[165,111],[127,143],[191,143],[100,176],[218,176]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3.5"/>`).join('')+'</g></svg><div class="rep-counter"><small>SQUATS</small><b>08<span> reps</span></b></div>';
    case 'terminal': return '<div class="terminal-window"><div class="terminal-top">● ● ● <span>hurl — terminal</span></div><p><em>~</em> hurl https://example.com</p><p class="terminal-response">HTTP/1.1 200 OK<br>content-type: text/html</p><p><em>✓</em> Transfer complete <span class="cursor">▌</span></p></div>';
    case 'names': return '<div class="name-reel"><span>Alex</span><b>Jamie <i>✦</i></b><span>Sam</span></div><span class="confetti c1">✦</span><span class="confetti c2">✧</span><span class="confetti c3">✦</span>';
    case 'mural': return '<div class="mural-canvas"><span class="doodle d1">hello!</span><span class="doodle d2">✳</span><span class="doodle d3">〰</span><span class="doodle d4">☺</span><span class="doodle d5">✴</span><span class="doodle d6">make<br>something.</span></div><div class="paint-tools"><i></i><i></i><i></i><i></i><i></i></div>';
    case 'morse': return '<div class="morse-art">••• &nbsp; ——— &nbsp; •••<small>A TOUCH OF LIGHT.</small></div>';
    case 'rack': return '<div class="server-rack">'+Array.from({length:4},()=>'<div><span>••••••••••••</span><i></i><i></i></div>').join('')+'</div>';
    default: return `<div class="code-art"><span>${esc(r.language || 'EXPERIMENT')}</span><b>${r.fork ? '⑂' : '{ }'}</b><small>${esc(r.name)}</small></div>`;
  }
}

document.querySelector('#app').innerHTML = `
  <header class="site-header"><a class="brand" href="#" aria-label="Bahdah Shin home"><span class="brand-mark">b<span>.</span></span> Bahdah Shin<span class="brand-slash">/</span><span class="brand-caption">portfolio</span></a><nav aria-label="Main navigation"><a class="nav-active" href="#projects">Projects</a><a href="#about">About</a><a class="github-link" href="https://github.com/bahdahshin" target="_blank" rel="noreferrer">GitHub ${icon('arrow',16)}</a></nav></header>
  <main><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> CURIOUS BY DEFAULT. BUILDING BY CHOICE.</div><h1 id="hero-title">Small ideas.<br><span>Working software.</span></h1><p>A collection of things I’ve built, explored, and shared.<br>From everyday tools to experiments down the rabbit hole.</p><div class="hero-meta"><span>${icon('pin',15)} ${esc(data.profile.location)}</span><span class="meta-divider"></span><a href="https://github.com/bahdahshin" target="_blank" rel="noreferrer">${icon('github',16)} @bahdahshin ${icon('arrow',13)}</a></div></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><span class="orbit-point point-one"></span><span class="orbit-point point-two"></span><div class="floating-tag tag-one">&lt; curiosity /&gt;</div><div class="hero-symbol">✳</div><div class="floating-tag tag-two"><span class="status-dot"></span> always a work in progress</div><span class="art-coordinate">IDEA → BUILD → ITERATE</span></div></section>
  <section id="projects" class="project-section" aria-labelledby="section-title"><div class="section-heading"><div><span class="eyebrow section-eyebrow">THE OPEN-SOURCE NOTEBOOK</span><h2 id="section-title">Projects & experiments<span>.</span></h2></div><span class="repo-total">${repos.length} public repositories ${icon('github',17)}</span></div>
  <div class="catalog-tabs" role="tablist" aria-label="Repository type"><button id="projects-tab" role="tab" aria-controls="catalog-panel" data-tab="projects">${icon('grid',16)} My projects <span>${counts.projects}</span></button><button id="forks-tab" role="tab" aria-controls="catalog-panel" data-tab="forks">${icon('fork',16)} Forks <span>${counts.forks}</span></button><span class="tab-note">Built with curiosity. Shared on GitHub.</span></div>
  <div id="catalog-panel" role="tabpanel"><div class="filters"><label class="search">${icon('search',18)}<input id="search" type="search" placeholder="Find a project…" aria-label="Search repositories"><kbd>/</kbd></label><div class="selects"><label><span class="sr-only">Filter by language</span><select id="language"><option value="">All languages</option></select></label><label><span class="sr-only">Sort repositories</span><select id="sort"><option value="curated">Featured first</option><option value="updated">Recently updated</option><option value="stars">Most stars</option><option value="name">Name: A–Z</option></select></label></div></div><div class="result-line"><p id="result-count" role="status"></p><span id="collection-note"></span></div><div id="project-grid" class="project-grid"></div></div></section>
  <section id="about" class="about"><div><span class="eyebrow">A LITTLE ABOUT ME</span><h2>Hi, I’m Bahdah<span>.</span></h2><p>My repositories explore web apps, native tools, computer vision, and home infrastructure. This is a place for the useful things, the playful things, and everything I learn along the way.</p></div><a href="https://github.com/bahdahshin" target="_blank" rel="noreferrer">Explore my GitHub ${icon('arrow')}</a></section></main><footer><span>© ${new Date().getFullYear()} Bahdah Shin</span><span>Made of small ideas & a lot of commits.</span><a href="#">Back to top ↑</a></footer>`;

function render() {
  document.querySelectorAll('[data-tab]').forEach(el => { const active = el.dataset.tab === state.tab; el.setAttribute('aria-selected', active); el.tabIndex = active ? 0 : -1; });
  document.querySelector('#catalog-panel').setAttribute('aria-labelledby', `${state.tab}-tab`);
  const visible = selectRepos(repos, state);
  document.querySelector('#result-count').textContent = `Showing ${visible.length} ${state.tab === 'forks' ? 'forks' : 'projects'}`;
  document.querySelector('#collection-note').textContent = state.tab === 'forks' ? 'Forked repositories · credit belongs to their original authors' : 'A few favorites first, then the rest of the journey';
  document.querySelector('#project-grid').innerHTML = visible.length ? visible.map(r => `<article class="project-card"><a class="project-art art-${r.art}" href="${esc(r.html_url)}" target="_blank" rel="noreferrer" aria-label="Explore ${esc(r.title)} on GitHub"><div aria-hidden="true" class="art-inner">${artwork(r)}</div><span class="art-open">${icon('arrow',18)}</span>${r.name === 'hanzi-lookup' ? '<span class="featured-badge">✧ Featured project</span>' : ''}</a><div class="card-body"><div class="card-category">${esc(r.category)}${r.fork ? `<span>${icon('fork',12)} Fork</span>` : r.archived ? '<span>Archived</span>' : ''}</div><h3><a href="${esc(r.html_url)}" target="_blank" rel="noreferrer">${esc(r.title)} ${icon('arrow',18)}</a></h3><p>${esc(r.summary)}</p><div class="card-footer"><span class="language"><i style="--language:${({ JavaScript:'#d8bd4c', Rust:'#b87a62', Python:'#5a90b4', Swift:'#dc846b', Haskell:'#9c83bb', HTML:'#d87659', C:'#8496aa', 'C++':'#c17891', 'C#':'#8eae65', Shell:'#8daa6c' })[r.language] || '#a6ada3'}"></i>${esc(r.language || 'Other')}</span><div>${r.stargazers_count ? `<span class="stars">${icon('star',13)} ${r.stargazers_count}</span>` : ''}${r.homepage && /^https?:\/\//.test(r.homepage) ? `<a href="${esc(r.homepage)}" target="_blank" rel="noreferrer">${r.fork ? 'Website' : 'Visit site'} ${icon('arrow',13)}</a>` : `<a href="${esc(r.html_url)}" target="_blank" rel="noreferrer">Source ${icon('github',14)}</a>`}</div></div></div></article>`).join('') : '<div class="empty-state"><span>⌕</span><h3>No projects found</h3><p>Try another search or a different language.</p><button id="reset-filters">Clear filters</button></div>';
  document.querySelector('#reset-filters')?.addEventListener('click', () => { state.query = ''; state.language = ''; document.querySelector('#search').value = ''; document.querySelector('#language').value = ''; render(); });
}
function setTab(tab, focus = false) { state.tab = tab; state.language = ''; history.replaceState(null, '', tab === 'forks' ? '#forks' : '#projects'); populateLanguages(); render(); if (focus) document.querySelector(`#${tab}-tab`).focus(); }
function populateLanguages() { document.querySelector('#language').innerHTML = '<option value="">All languages</option>' + [...new Set(repos.filter(r=>r.fork === (state.tab === 'forks')).map(r=>r.language).filter(Boolean))].sort().map(l=>`<option value="${esc(l)}">${esc(l)}</option>`).join(''); }
document.querySelectorAll('[data-tab]').forEach(el => { el.addEventListener('click', () => setTab(el.dataset.tab)); el.addEventListener('keydown', e => { if (['ArrowLeft','ArrowRight','Home','End'].includes(e.key)) { e.preventDefault(); setTab(e.key === 'Home' ? 'projects' : e.key === 'End' ? 'forks' : state.tab === 'projects' ? 'forks' : 'projects', true); } }); });
document.querySelector('#search').addEventListener('input', e => { state.query = e.target.value; render(); });
document.querySelector('#language').addEventListener('change', e => { state.language = e.target.value; render(); });
document.querySelector('#sort').addEventListener('change', e => { state.sort = e.target.value; render(); });
document.addEventListener('keydown', e => { if (e.key === '/' && !['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)) { e.preventDefault(); document.querySelector('#search').focus(); } });
window.addEventListener('hashchange', () => { if (['#forks','#projects'].includes(location.hash)) setTab(location.hash.slice(1)); });
populateLanguages(); render();
